language: node_js
node_js:
  - "8"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  
addons:
  apt:
    packages:
      - libcurl4-openssl-dev  
before_script:
  - npm install
script: npm run test
