# Fabrizio Duroni Website Jekyll config file.
#

########## Data

title: Fabrizio Duroni

author: Fabrizio Duroni

email: fabrizio.duroni@gmail.com

description: >
 Fabrizio Duroni 'Chicio' official site with profile details. Main skills: mobile application development,
 computer graphics, web development.

url: https://www.fabrizioduroni.it

github_username: chicio

twitter:
  username: chicio86

facebook:
  app_id: 443203399348229
  publisher: https://www.facebook.com/fabrizio.duroni

logo: /assets/images/fabrizio-duroni.jpg

social:
  name: Fabrizio Duroni
  links:
    - https://twitter.com/chicio86
    - https://www.facebook.com/fabrizio.duroni
    - https://www.linkedin.com/in/fabrizio-duroni-947a9b35/
    - https://plus.google.com/+FabrizioDuroni
    - https://github.com/chicio
    - https://it.pinterest.com/chicio86/

lang: en_US

image: /assets/images/fabrizio-duroni.jpg

nav:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog/"
  - name: "About Me"
    url: "/2017/05/10/about-me.html"

########## Configuration

timezone: Europe/Rome

future: false

defaults:
  - scope:
      path: "" # defaults for all files
    values:
      image: /assets/images/fabrizio-duroni.jpg

paginate: 5
paginate_path: /blog/page:num/

# Debug options
# minify_html: false
# limit_posts: 1

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Jemoji
emoji:
  src: "/assets/images/"

# RSS Feed
feed_items: 30
feed_update_period: monthly
feed_update_frequency: 2

# Plugin (gems) used by Jekyll
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - octopress-minify-html
  - jekyll-paginate
  - jemoji

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - gulpfile.babel.js
  - material
  - LICENSE.md
  - README.md
  - dependencies-home.html
  - dependencies-blog.html
  - CNAME
