name: fabrizioduroni.it

on:
  push:
    branches: 
      - '*'
  schedule:
    - cron: '0 18 * * *' 

jobs:
  build-and-test:      
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node  
        uses: actions/setup-node@v1
        with:
          node-version: '13'        
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm 
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-          
      - name: Build and Test    
        run: |
          npm run setup
          npm run test
      - name: Lighthouse CI
        run: lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"        
