name: Lighthouse

on:
  push:
    branches: 
      - '*'
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  build-and-test:      
    name: Lighthouse Audit
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node  
        uses: actions/setup-node@v1
        with:
          node-version: '13'                 
      - name: Lhci
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://www.fabrizioduroni.it
            https://www.fabrizioduroni.it/blog/
          configPath: './.lighthouserc.json'  
          uploadArtifacts: true
          temporaryPublicStorage: true                
